# Generated by Django 5.0.1 on 2024-02-01 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organisationtype', models.CharField(choices=[('Schule', 'Schule'), ('Verein', 'Verein'), ('Uni', 'Uni'), ('Projekt', 'Projekt')], default='Schule', max_length=20)),
                ('organisation', models.CharField(max_length=50, null=True)),
                ('schoolclass', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('initals', models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Divers', 'Divers')], default='Herr', max_length=20)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('arrival_date', models.DateTimeField(null=True)),
                ('response_untill', models.DateTimeField(null=True)),
                ('remark', models.CharField(blank=True, max_length=800, null=True)),
                ('busplan', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
