# Generated by Django 5.0.1 on 2024-01-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='reservation',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
    ]
