# Generated by Django 5.0.1 on 2024-02-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_record_uuid_alter_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='traveldetail',
            field=models.CharField(choices=[('San Pepelone Reisebus', 'San Pepelone Reisebus'), ('Eigener Bus', 'Eigener Bus'), ('Bahn', 'Bahn'), ('PKW', 'PKW')], default='Eigener Bus', max_length=40),
        ),
    ]
