# Generated by Django 5.0.1 on 2024-02-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_record_planned_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='amount_organizer_female',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='amount_organizer_male',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='amount_students_female',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='amount_students_male',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='eventpackage',
            field=models.CharField(choices=[('A - Ausflugspaket', 'A - Ausflugspaket'), ('B - Ausflugspaket', 'B - Ausflugspaket')], default='Eigener Bus', max_length=40),
        ),
    ]
