# Generated by Django 5.0.1 on 2024-02-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_record_amount_organizer_female_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausflugspaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emailtemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='eventpackage',
        ),
        migrations.AddField(
            model_name='record',
            name='ausflugspaket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ausflugspaket'),
        ),
        migrations.CreateModel(
            name='Subpaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=50, null=True)),
                ('ausflugspaket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ausflugspaket')),
            ],
        ),
    ]
