# Generated by Django 5.0.1 on 2024-02-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_ausflugspaket_emailtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausflugspaket',
            name='content',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='subpaket',
            name='content',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
    ]
