# Generated by Django 5.0.1 on 2024-02-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_ausflugspaket_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausflugspaket',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='subpaket',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
    ]
