# Generated by Django 5.0.1 on 2024-02-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_record_arrival_date_alter_record_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('EMAIL SEND', 'EMAIL SEND'), ('ANSWERED', 'ANSWERED'), ('FINISH', 'FINISH')], default='CREATED', max_length=20),
        ),
    ]
