# Generated by Django 5.0.1 on 2024-02-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_record_initals_alter_record_schoolclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='ausflugspaket',
        ),
        migrations.AddField(
            model_name='record',
            name='ausflugspaket',
            field=models.ManyToManyField(related_name='record_ausflugspaket', to='website.ausflugspaket'),
        ),
    ]
