# Generated by Django 5.0.1 on 2024-02-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_record_ausflugspaket_record_ausflugspaket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='ausflugspaket',
        ),
        migrations.AddField(
            model_name='record',
            name='ausflugspaket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ausflugspaket'),
        ),
    ]
