# Generated by Django 5.0.1 on 2024-02-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_record_ausflugspaket_record_ausflugspaket'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='subpakete',
            field=models.ManyToManyField(blank=True, to='website.subpaket'),
        ),
    ]
