# Generated by Django 5.0.1 on 2024-02-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_record_subpakete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='subpakete',
            new_name='subpaket',
        ),
    ]
