# Generated by Django 5.0.1 on 2024-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_email_alter_record_subpaket'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('event_type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Error', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='bezeichnung',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='content',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
