# Generated by Django 5.0.1 on 2024-02-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_emaillog_remove_emailtemplate_bezeichnung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='remark_client',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
