# Generated by Django 5.0.1 on 2024-02-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_record_remark_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='organisation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
