# Generated by Django 5.0.1 on 2024-02-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_record_organisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.DeleteModel(
            name='Emailtemplate',
        ),
    ]
