# Generated by Django 5.0.1 on 2024-02-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_record_vdws_schein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='vdws_schein',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
