# Generated by Django 5.0.1 on 2024-02-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_record_vdws_schein'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='planned_depature_time',
            field=models.CharField(blank=True, choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30')], default=None, max_length=5, null=True),
        ),
    ]
