# Generated by Django 5.0.1 on 2024-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_record_organisationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='organisationtype',
            field=models.CharField(blank=True, choices=[('Schule', 'Schule'), ('Verein', 'Verein'), ('Uni', 'Uni'), ('Projekt', 'Projekt')], default='', max_length=20, null=True),
        ),
    ]
