# Generated by Django 5.0.1 on 2024-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_record_organisationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, choices=[('UNANSWERED', 'UNANSWERED'), ('EMAIL SEND', 'EMAIL SEND'), ('ANSWERED', 'ANSWERED'), ('FINISH', 'FINISH')], default='UNANSWERED', max_length=20),
        ),
    ]
