# Generated by Django 5.0.1 on 2024-02-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='traveldetail',
            field=models.CharField(blank=True, choices=[('bitte wählen', 'bitte wählen'), ('San Pepelone Reisebus', 'San Pepelone Reisebus'), ('Eigener Bus', 'Eigener Bus'), ('Bahn', 'Bahn'), ('PKW', 'PKW')], default='bitte wählen', max_length=40),
        ),
    ]
