# Generated by Django 5.0.1 on 2024-02-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_ausflugspaket_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount_organizer_female',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount_organizer_male',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount_students_female',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount_students_male',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='traveldetail',
            field=models.CharField(blank=True, choices=[('San Pepelone Reisebus', 'San Pepelone Reisebus'), ('Eigener Bus', 'Eigener Bus'), ('Bahn', 'Bahn'), ('PKW', 'PKW')], default='Eigener Bus', max_length=40),
        ),
    ]
