# Generated by Django 5.0.1 on 2024-02-02 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_record_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='initals',
            field=models.CharField(blank=True, choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Divers', 'Divers')], default='Herr', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='schoolclass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATED', 'CREATED'), ('EMAIL SEND', 'EMAIL SEND'), ('ANSWERED', 'ANSWERED'), ('FINISH', 'FINISH')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
