# Generated by Django 5.0.1 on 2024-02-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='vdws_schein',
            field=models.BooleanField(default=False),
        ),
    ]
