# Generated by Django 5.0.1 on 2024-02-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_record_planned_depature_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='planned_depature_time',
            new_name='planned_departure_time',
        ),
    ]
